# Generated by Django 3.2.8 on 2022-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandacalluser',
            name='notificationToken',
            field=models.TextField(),
        ),
    ]
